export GENIE_FQ_DIR=/project/software/GENIE_v3_06_00/Generator
export GENIE_VERSION=3_06_00
export GENIE=${GENIE_FQ_DIR}
export GENIE_LIB=${GENIE_FQ_DIR}/lib
export GENIE_INC=${GENIE_FQ_DIR}/install/include/GENIE/
export GENIE_REWEIGHT=/project/software/GENIEReWeight_v1_04_00/Reweight
export LD_LIBRARY_PATH=${GENIE_FQ_DIR}/lib/:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${GENIE_REWEIGHT}/lib/:${LD_LIBRARY_PATH}
export PATH=${GENIE_FQ_DIR}/bin/:${PATH}
export PATH=${GENIE_REWEIGHT}/bin/:${PATH}
export ROOT_INCLUDE_PATH=${GENIE_FQ_DIR}/include/GENIE/:${ROOT_INCLUDE_PATH}
export CMAKE_PREFIX_PATH=${GENIE_FQ_DIR}:${CMAKE_PREFIX_PATH}
export PKG_CONFIG_PATH=${GENIE_FQ_DIR}:${PKG_CONFIG_PATH}
export GENIE_XSEC_DIR=$GENIE_FQ_DIR/xsec/G1810a0211a-k250-e1000/
export GENIE_XSEC_FILE=$GENIE_XSEC_DIR/gxspl-NUbig.xml
export GENIE_XSEC_TUNE=G18_10a_02_11a
export PYTHIA6_LIB_DIR=/usr/lib/
#GENIE CONVERTED
export ROOT_INCLUDE_PATH=/project/software/nusystematics/install/include:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${GENIE_INC}:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${fhiclcpp_ROOT}/include/:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${cetlib_ROOT}/include/:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${cetlib_except_ROOT}/include:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${hep_concurrency_ROOT}/include:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${Boost_INCLUDE_DIR}:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${SQLite3_INLUDE_DIR}:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${TBB_INCLUDE_DIR}:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${NUISANCE_INCLUDE_DIR}:$ROOT_INCLUDE_PATH
#ROOT IS THE SAME?
export Boost_INCLUDE_DIR=/usr/include/boost1.78/
export Boost_LIBRARY=/usr/lib64/
export SQLite3_INCLUDE_DIR=/usr/include
export SQLite3_LIBRARY=/usr/lib64/
#BOOST IS THE SAME
export fhiclcpp_ROOT=/home/project/nuisance/nusyst_dev/fhicl-cpp-standalone/build-mazen/fhicl-cpp-install/
export PATH=${fhiclcpp_ROOT}/bin/:${PATH}
export LD_LIBRARY_PATH=${fhiclcpp_ROOT}/lib/:${LD_LIBRARY_PATH}
export cetlib_ROOT=/home/project/nuisance/nusyst_dev/fhicl-cpp-standalone/build-mazen/cetlib-install/
export PATH=${cetlib_ROOT}/bin/:${PATH}
export LD_LIBRARY_PATH=${cetlib_ROOT}/lib/:${LD_LIBRARY_PATH}
export cetlib_except_ROOT=/home/project/nuisance/nusyst_dev/fhicl-cpp-standalone/build-mazen/cetlib-except-install/
export PATH=${cetlib_except_ROOT}/bin/:${PATH}
export LD_LIBRARY_PATH=${cetlib_except_ROOT}/lib/:${LD_LIBRARY_PATH}
export hep_concurrency_ROOT=/home/project/nuisance/nusyst_dev/fhicl-cpp-standalone/build-mazen/hep-concurrency-install
export PATH=${hep_concurrency_ROOT}/bin/:${PATH}
export LD_LIBRARY_PATH=${hep_concurrency_ROOT}/lib/:${LD_LIBRARY_PATH}
#^^ FIX THESE
export CPLUS_INCLUDE_PATH=/home/project/nuisance/nusyst_dev/nusystematics/build/Linux/include/:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${GENIE_INC}:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${fhiclcpp_ROOT}/include/:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${cetlib_ROOT}/include/:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${cetlib_except_ROOT}/include:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${hep_concurrency_ROOT}/include:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${Boost_INCLUDE_DIR}:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${SQLite3_INLUDE_DIR}:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${TBB_INCLUDE_DIR}:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/home/project/ROOT/v6_26_06_pythia6/include:$CPLUS_INCLUDE_PATH
#export CPLUS_INCLUDE_PATH=/home/mazen_malak/gcc-dev/gcc-install/include/c++/9.3.0:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${NUISANCE_INCLUDE_DIR}:$CPLUS_INCLUDE_PATH
# FIX THESE^ ?
### Nuisance Code breaks if I don't include this??
export NUISANCE=/project/software/nuisance/build/Linux
export PATH=$NUISANCE/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NUISANCE/lib
export PKG_CONFIG_PATH=/project/software/neut/build/Linux:$PKG_CONFIG_PATH
source /project/software/nuisance/install/setup.sh
### nusystematics
export NUSYSTEMATICS=/project/software/nusystematics/install
export PATH=$NUSYSTEMATICS/bin:$PATH
export LD_LIBRARY_PATH=$NUSYSTEMATICS/lib:$LD_LIBRARY_PATH