### Neut
export NEUT=/your/path/too/neut/build/Linux
export PATH=$PATH:$NEUT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NEUT/lib
export NEUT_VERSION=x.x.x
### Nuisance
export NUISANCE=/your/path/too/nuisance/build/Linux
export PATH=$NUISANCE/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NUISANCE/lib
export PKG_CONFIG_PATH=/your/path/too/neut/build/Linux:$PKG_CONFIG_PATH
source /your/path/too/nuisance/install/setup.sh
### NIWGReWeight
export NIWGRW_FQ_DIR=/your/path/too/NIWGReWeight
export NIWGRW=${NIWGRW_FQ_DIR}/build/Linux
source /your/path/too/NIWGReWeight/build/Linux/bin/setup.NIWG.sh
## T2KReWeight
export T2KRW=/your/path/too/T2KReWeight24.12/build/Linux
source /your/path/too/T2KReWeight24.12/build/Linux/bin/setup.T2K.sh
## LHAPDF
export LHAPDF_LIB_DIR=/usr/lib64
export LHAPDF_INC_DIR=/usr/include/LHAPDF
#CPP include
export CPLUS_INCLUDE_PATH=/path/too/nuisance/nusyst_dev/nusystematics/build/Linux/include/:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${fhiclcpp_ROOT}/include/:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${cetlib_ROOT}/include/:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${NIWGRW}/include/:$CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=${T2KRW}/include/:$CPLUS_INCLUDE_PATH
### ROOT
export ROOT_INCLUDE_PATH=${fhiclcpp_ROOT}/include/:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${cetlib_ROOT}/include/:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${NIWGRW}/include:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${T2KRW}/include:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${NEUT}/include:$ROOT_INCLUDE_PATH
export ROOT_INCLUDE_PATH=${NUISANCE_INCLUDE_DIR}:$ROOT_INCLUDE_PATH

# Source ROOT setup
source /path/too/ROOT/v6_30_02_cxx17/bin/thisroot.sh
source /your/path/too/neut/build/Linux/setup.sh
export ROOTSYS=/path/too/ROOT/v6_30_02_cxx17
